// Package langtoolapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package langtoolapi

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
)

// Defines values for PostCheckFormdataBodyLevel.
const (
	Default PostCheckFormdataBodyLevel = "default"
	Picky   PostCheckFormdataBodyLevel = "picky"
)

// Valid indicates whether the value is a known member of the PostCheckFormdataBodyLevel enum.
func (e PostCheckFormdataBodyLevel) Valid() bool {
	switch e {
	case Default:
		return true
	case Picky:
		return true
	default:
		return false
	}
}

// Language defines model for Language.
type Language struct {
	// Code a language code like 'en'
	Code string `json:"code"`

	// LongCode a language code like 'en-US' or 'ca-ES-valencia'
	LongCode string `json:"longCode"`

	// Name a language name like 'French' or 'English (Australia)'
	Name string `json:"name"`
}

// Match defines model for Match.
type Match struct {
	Context struct {
		// Length The length of the error in characters in the context.
		Length int `json:"length"`

		// Offset The 0-based character offset of the error in the context text.
		Offset int `json:"offset"`

		// Text Context of the error.
		Text string `json:"text"`
	} `json:"context"`

	// Length The length of the error in characters.
	Length int `json:"length"`

	// Message Message about the error displayed to the user.
	Message string `json:"message"`

	// Offset The 0-based character offset of the error in the text.
	Offset int `json:"offset"`

	// Replacements Replacements that might correct the error.
	Replacements []struct {
		// Value the replacement string
		Value *string `json:"value,omitempty"`
	} `json:"replacements"`
	Rule *struct {
		Category struct {
			// Id A category's identifier that's unique for this language.
			Id *string `json:"id,omitempty"`

			// Name A short description of the category.
			Name *string `json:"name,omitempty"`
		} `json:"category"`
		Description string `json:"description"`

		// Id A rule's identifier that's unique for this language.
		Id string `json:"id"`

		// IssueType The Localization Quality Issue Type.
		IssueType *string `json:"issueType,omitempty"`

		// SubId An optional sub identifier of the rule.
		SubId *string `json:"subId,omitempty"`

		// Urls An optional array of URLs with a more detailed description of the error.
		Urls *[]struct {
			// Value the URL
			Value *string `json:"value,omitempty"`
		} `json:"urls,omitempty"`
	} `json:"rule,omitempty"`

	// Sentence The sentence the error occurred in
	Sentence string `json:"sentence"`

	// ShortMessage An optional shorter version of 'message'.
	ShortMessage *string `json:"shortMessage,omitempty"`
}

// PostCheckFormdataBody defines parameters for PostCheck.
type PostCheckFormdataBody struct {
	// ApiKey Set to get Premium API access: your API key
	ApiKey *string `form:"apiKey,omitempty" json:"apiKey,omitempty"`

	// Data The text to be checked, given as a JSON document that specifies what's text and what's markup. This or 'text' is required. Markup will be ignored when looking for errors.
	Data *string `form:"data,omitempty" json:"data,omitempty"`

	// Dicts Comma-separated list of dictionaries to include words from; uses special default dictionary if this is unset
	Dicts *string `form:"dicts,omitempty" json:"dicts,omitempty"`

	// DisabledCategories IDs of categories to be disabled, comma-separated
	DisabledCategories *string `form:"disabledCategories,omitempty" json:"disabledCategories,omitempty"`

	// DisabledRules IDs of rules to be disabled, comma-separated
	DisabledRules *string `form:"disabledRules,omitempty" json:"disabledRules,omitempty"`

	// EnabledCategories IDs of categories to be enabled, comma-separated
	EnabledCategories *string `form:"enabledCategories,omitempty" json:"enabledCategories,omitempty"`

	// EnabledOnly If true, only the rules and categories whose IDs are specified with `enabledRules` or `enabledCategories` are enabled.
	EnabledOnly *bool `form:"enabledOnly,omitempty" json:"enabledOnly,omitempty"`

	// EnabledRules IDs of rules to be enabled, comma-separated.
	EnabledRules *string `form:"enabledRules,omitempty" json:"enabledRules,omitempty"`

	// Language A language code like `en-US`, `de-DE`, `fr`, or `auto` to guess the language automatically (see `preferredVariants` below). For languages with variants (English, German, Portuguese) spell checking will only be activated when you specify the variant, e.g. `en-GB` instead of just `en`.
	Language *string `form:"language,omitempty" json:"language,omitempty"`

	// Level If set to `picky`, additional rules will be activated, i.e. rules that you might only find useful when checking formal text.
	Level *PostCheckFormdataBodyLevel `form:"level,omitempty" json:"level,omitempty"`

	// MotherTongue A language code of the user's native language, enabling false friends checks for some language pairs.
	MotherTongue *string `form:"motherTongue,omitempty" json:"motherTongue,omitempty"`

	// PreferredVariants Comma-separated list of preferred language variants. The language detector used with `language=auto` can detect e.g. English, but it cannot decide whether British English or American English is used. Thus this parameter can be used to specify the preferred variants like `en-GB` and `de-AT`. Only available with `language=auto`.
	PreferredVariants *string `form:"preferredVariants,omitempty" json:"preferredVariants,omitempty"`

	// Text The text to be checked. This or 'data' is required.
	Text *string `form:"text,omitempty" json:"text,omitempty"`

	// Username Set to get Premium API access: Your username/email as used to log in at languagetool.org.
	Username *string `form:"username,omitempty" json:"username,omitempty"`
}

// PostCheckFormdataBodyLevel defines parameters for PostCheck.
type PostCheckFormdataBodyLevel string

// GetWordsParams defines parameters for GetWords.
type GetWordsParams struct {
	// Offset Offset of where to start in the list of words. Defaults to 0.
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`

	// Limit Maximum number of words to return. Defaults to 10.
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Username Your username as used to log in at languagetool.org.
	Username string `form:"username" json:"username"`

	// ApiKey Your API key
	ApiKey string `form:"apiKey" json:"apiKey"`

	// Dicts Comma-separated list of dictionaries to include words from; uses special default dictionary if this is unset
	Dicts *string `form:"dicts,omitempty" json:"dicts,omitempty"`
}

// PostWordsAddFormdataBody defines parameters for PostWordsAdd.
type PostWordsAddFormdataBody struct {
	// ApiKey Your API key
	ApiKey string `form:"apiKey" json:"apiKey"`

	// Dict Name of the dictionary to add the word to; non-existent dictionaries are created after calling this; if unset, adds to special default dictionary
	Dict *string `form:"dict,omitempty" json:"dict,omitempty"`

	// Username Your username as used to log in at languagetool.org.
	Username string `form:"username" json:"username"`

	// Word The word to be added. Must not be a phrase, i.e. cannot contain white space. The word is added to a global dictionary that applies to all languages.
	Word string `form:"word" json:"word"`
}

// PostWordsDeleteFormdataBody defines parameters for PostWordsDelete.
type PostWordsDeleteFormdataBody struct {
	// ApiKey Your API key
	ApiKey string `form:"apiKey" json:"apiKey"`

	// Dict Name of the dictionary to remove the word from; if the dictionary is empty upon calling this, it is deleted; if unset, removes from special default dictionary
	Dict *string `form:"dict,omitempty" json:"dict,omitempty"`

	// Username Your username as used to log in at languagetool.org.
	Username string `form:"username" json:"username"`

	// Word The word to be removed.
	Word string `form:"word" json:"word"`
}

// PostCheckFormdataRequestBody defines body for PostCheck for application/x-www-form-urlencoded ContentType.
type PostCheckFormdataRequestBody PostCheckFormdataBody

// PostWordsAddFormdataRequestBody defines body for PostWordsAdd for application/x-www-form-urlencoded ContentType.
type PostWordsAddFormdataRequestBody PostWordsAddFormdataBody

// PostWordsDeleteFormdataRequestBody defines body for PostWordsDelete for application/x-www-form-urlencoded ContentType.
type PostWordsDeleteFormdataRequestBody PostWordsDeleteFormdataBody

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// PostCheckWithBody request with any body
	PostCheckWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostCheckWithFormdataBody(ctx context.Context, body PostCheckFormdataRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetLanguages request
	GetLanguages(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetWords request
	GetWords(ctx context.Context, params *GetWordsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostWordsAddWithBody request with any body
	PostWordsAddWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostWordsAddWithFormdataBody(ctx context.Context, body PostWordsAddFormdataRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostWordsDeleteWithBody request with any body
	PostWordsDeleteWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostWordsDeleteWithFormdataBody(ctx context.Context, body PostWordsDeleteFormdataRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) PostCheckWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostCheckRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostCheckWithFormdataBody(ctx context.Context, body PostCheckFormdataRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostCheckRequestWithFormdataBody(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetLanguages(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetLanguagesRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetWords(ctx context.Context, params *GetWordsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetWordsRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostWordsAddWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostWordsAddRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostWordsAddWithFormdataBody(ctx context.Context, body PostWordsAddFormdataRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostWordsAddRequestWithFormdataBody(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostWordsDeleteWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostWordsDeleteRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostWordsDeleteWithFormdataBody(ctx context.Context, body PostWordsDeleteFormdataRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostWordsDeleteRequestWithFormdataBody(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewPostCheckRequestWithFormdataBody calls the generic PostCheck builder with application/x-www-form-urlencoded body
func NewPostCheckRequestWithFormdataBody(server string, body PostCheckFormdataRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	bodyStr, err := runtime.MarshalForm(body, nil)
	if err != nil {
		return nil, err
	}
	bodyReader = strings.NewReader(bodyStr.Encode())
	return NewPostCheckRequestWithBody(server, "application/x-www-form-urlencoded", bodyReader)
}

// NewPostCheckRequestWithBody generates requests for PostCheck with any type of body
func NewPostCheckRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/check")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetLanguagesRequest generates requests for GetLanguages
func NewGetLanguagesRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/languages")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetWordsRequest generates requests for GetWords
func NewGetWordsRequest(server string, params *GetWordsParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/words")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.Offset != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "offset", *params.Offset, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.Limit != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "limit", *params.Limit, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "username", params.Username, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "apiKey", params.ApiKey, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: "password"}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if params.Dicts != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "dicts", *params.Dicts, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostWordsAddRequestWithFormdataBody calls the generic PostWordsAdd builder with application/x-www-form-urlencoded body
func NewPostWordsAddRequestWithFormdataBody(server string, body PostWordsAddFormdataRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	bodyStr, err := runtime.MarshalForm(body, nil)
	if err != nil {
		return nil, err
	}
	bodyReader = strings.NewReader(bodyStr.Encode())
	return NewPostWordsAddRequestWithBody(server, "application/x-www-form-urlencoded", bodyReader)
}

// NewPostWordsAddRequestWithBody generates requests for PostWordsAdd with any type of body
func NewPostWordsAddRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/words/add")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewPostWordsDeleteRequestWithFormdataBody calls the generic PostWordsDelete builder with application/x-www-form-urlencoded body
func NewPostWordsDeleteRequestWithFormdataBody(server string, body PostWordsDeleteFormdataRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	bodyStr, err := runtime.MarshalForm(body, nil)
	if err != nil {
		return nil, err
	}
	bodyReader = strings.NewReader(bodyStr.Encode())
	return NewPostWordsDeleteRequestWithBody(server, "application/x-www-form-urlencoded", bodyReader)
}

// NewPostWordsDeleteRequestWithBody generates requests for PostWordsDelete with any type of body
func NewPostWordsDeleteRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/words/delete")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// PostCheckWithBodyWithResponse request with any body
	PostCheckWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostCheckResponse, error)

	PostCheckWithFormdataBodyWithResponse(ctx context.Context, body PostCheckFormdataRequestBody, reqEditors ...RequestEditorFn) (*PostCheckResponse, error)

	// GetLanguagesWithResponse request
	GetLanguagesWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetLanguagesResponse, error)

	// GetWordsWithResponse request
	GetWordsWithResponse(ctx context.Context, params *GetWordsParams, reqEditors ...RequestEditorFn) (*GetWordsResponse, error)

	// PostWordsAddWithBodyWithResponse request with any body
	PostWordsAddWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostWordsAddResponse, error)

	PostWordsAddWithFormdataBodyWithResponse(ctx context.Context, body PostWordsAddFormdataRequestBody, reqEditors ...RequestEditorFn) (*PostWordsAddResponse, error)

	// PostWordsDeleteWithBodyWithResponse request with any body
	PostWordsDeleteWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostWordsDeleteResponse, error)

	PostWordsDeleteWithFormdataBodyWithResponse(ctx context.Context, body PostWordsDeleteFormdataRequestBody, reqEditors ...RequestEditorFn) (*PostWordsDeleteResponse, error)
}

type PostCheckResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		// Language The language used for checking the text.
		Language *struct {
			// Code ISO 639-1 code like 'en', 'en-US', or 'ca-ES-valencia'
			Code string `json:"code"`

			// DetectedLanguage The automatically detected text language.
			DetectedLanguage struct {
				// Code ISO 639-1 code like 'en', 'en-US', or 'ca-ES-valencia'.
				Code string `json:"code"`

				// Name Language name like 'French' or 'English (US)'.
				Name string `json:"name"`
			} `json:"detectedLanguage"`

			// Name Language name like 'French' or 'English (US)'.
			Name string `json:"name"`
		} `json:"language,omitempty"`
		Matches  *[]Match `json:"matches,omitempty"`
		Software *struct {
			// ApiVersion Version of this API response.
			ApiVersion int `json:"apiVersion"`

			// BuildDate Date when the software was built, e.g. '2016-05-25'.
			BuildDate string `json:"buildDate"`

			// Name Usually 'LanguageTool'.
			Name string `json:"name"`

			// Premium true if you're using a Premium account with all the premium text checks
			Premium *bool `json:"premium,omitempty"`

			// Status An optional warning, e.g. when the API format is not stable.
			Status *string `json:"status,omitempty"`

			// Version A version string like '3.3' or '3.4-SNAPSHOT'.
			Version string `json:"version"`
		} `json:"software,omitempty"`
	}
}

// Status returns HTTPResponse.Status
func (r PostCheckResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostCheckResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r PostCheckResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetLanguagesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *[]Language
}

// Status returns HTTPResponse.Status
func (r GetLanguagesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetLanguagesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetLanguagesResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetWordsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		// Words array of words
		Words *[]string `json:"words,omitempty"`
	}
}

// Status returns HTTPResponse.Status
func (r GetWordsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetWordsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetWordsResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type PostWordsAddResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		// Added true if the word has been added. false means the word hasn't been added because it had been added before.
		Added *bool `json:"added,omitempty"`
	}
}

// Status returns HTTPResponse.Status
func (r PostWordsAddResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostWordsAddResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r PostWordsAddResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type PostWordsDeleteResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		// Deleted true if the word has been removed. false means the word hasn't been removed because it was not in the dictionary.
		Deleted *bool `json:"deleted,omitempty"`
	}
}

// Status returns HTTPResponse.Status
func (r PostWordsDeleteResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostWordsDeleteResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r PostWordsDeleteResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// PostCheckWithBodyWithResponse request with arbitrary body returning *PostCheckResponse
func (c *ClientWithResponses) PostCheckWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostCheckResponse, error) {
	rsp, err := c.PostCheckWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostCheckResponse(rsp)
}

func (c *ClientWithResponses) PostCheckWithFormdataBodyWithResponse(ctx context.Context, body PostCheckFormdataRequestBody, reqEditors ...RequestEditorFn) (*PostCheckResponse, error) {
	rsp, err := c.PostCheckWithFormdataBody(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostCheckResponse(rsp)
}

// GetLanguagesWithResponse request returning *GetLanguagesResponse
func (c *ClientWithResponses) GetLanguagesWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetLanguagesResponse, error) {
	rsp, err := c.GetLanguages(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetLanguagesResponse(rsp)
}

// GetWordsWithResponse request returning *GetWordsResponse
func (c *ClientWithResponses) GetWordsWithResponse(ctx context.Context, params *GetWordsParams, reqEditors ...RequestEditorFn) (*GetWordsResponse, error) {
	rsp, err := c.GetWords(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetWordsResponse(rsp)
}

// PostWordsAddWithBodyWithResponse request with arbitrary body returning *PostWordsAddResponse
func (c *ClientWithResponses) PostWordsAddWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostWordsAddResponse, error) {
	rsp, err := c.PostWordsAddWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostWordsAddResponse(rsp)
}

func (c *ClientWithResponses) PostWordsAddWithFormdataBodyWithResponse(ctx context.Context, body PostWordsAddFormdataRequestBody, reqEditors ...RequestEditorFn) (*PostWordsAddResponse, error) {
	rsp, err := c.PostWordsAddWithFormdataBody(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostWordsAddResponse(rsp)
}

// PostWordsDeleteWithBodyWithResponse request with arbitrary body returning *PostWordsDeleteResponse
func (c *ClientWithResponses) PostWordsDeleteWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostWordsDeleteResponse, error) {
	rsp, err := c.PostWordsDeleteWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostWordsDeleteResponse(rsp)
}

func (c *ClientWithResponses) PostWordsDeleteWithFormdataBodyWithResponse(ctx context.Context, body PostWordsDeleteFormdataRequestBody, reqEditors ...RequestEditorFn) (*PostWordsDeleteResponse, error) {
	rsp, err := c.PostWordsDeleteWithFormdataBody(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostWordsDeleteResponse(rsp)
}

// ParsePostCheckResponse parses an HTTP response from a PostCheckWithResponse call
func ParsePostCheckResponse(rsp *http.Response) (*PostCheckResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostCheckResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			// Language The language used for checking the text.
			Language *struct {
				// Code ISO 639-1 code like 'en', 'en-US', or 'ca-ES-valencia'
				Code string `json:"code"`

				// DetectedLanguage The automatically detected text language.
				DetectedLanguage struct {
					// Code ISO 639-1 code like 'en', 'en-US', or 'ca-ES-valencia'.
					Code string `json:"code"`

					// Name Language name like 'French' or 'English (US)'.
					Name string `json:"name"`
				} `json:"detectedLanguage"`

				// Name Language name like 'French' or 'English (US)'.
				Name string `json:"name"`
			} `json:"language,omitempty"`
			Matches  *[]Match `json:"matches,omitempty"`
			Software *struct {
				// ApiVersion Version of this API response.
				ApiVersion int `json:"apiVersion"`

				// BuildDate Date when the software was built, e.g. '2016-05-25'.
				BuildDate string `json:"buildDate"`

				// Name Usually 'LanguageTool'.
				Name string `json:"name"`

				// Premium true if you're using a Premium account with all the premium text checks
				Premium *bool `json:"premium,omitempty"`

				// Status An optional warning, e.g. when the API format is not stable.
				Status *string `json:"status,omitempty"`

				// Version A version string like '3.3' or '3.4-SNAPSHOT'.
				Version string `json:"version"`
			} `json:"software,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetLanguagesResponse parses an HTTP response from a GetLanguagesWithResponse call
func ParseGetLanguagesResponse(rsp *http.Response) (*GetLanguagesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetLanguagesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []Language
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetWordsResponse parses an HTTP response from a GetWordsWithResponse call
func ParseGetWordsResponse(rsp *http.Response) (*GetWordsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetWordsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			// Words array of words
			Words *[]string `json:"words,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParsePostWordsAddResponse parses an HTTP response from a PostWordsAddWithResponse call
func ParsePostWordsAddResponse(rsp *http.Response) (*PostWordsAddResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostWordsAddResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			// Added true if the word has been added. false means the word hasn't been added because it had been added before.
			Added *bool `json:"added,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParsePostWordsDeleteResponse parses an HTTP response from a PostWordsDeleteWithResponse call
func ParsePostWordsDeleteResponse(rsp *http.Response) (*PostWordsDeleteResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostWordsDeleteResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			// Deleted true if the word has been removed. false means the word hasn't been removed because it was not in the dictionary.
			Deleted *bool `json:"deleted,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}
